### ISSUE TITLE
Performance problemen in browser

### ISSUE THREAD

**Issue by aiunderstand** [Geodan/rws-imagine#101]
Moet uitvoerig geprofiled worden zit in een of meerdere onderdelen:
CPU (scripts)
GPU (rendering, effects)
Bandwith (textures, filters)

onderzoeken wat beste oplossing is in Unity. Waarschijnlijk Occlusion Culling, LoD switching, timed co-routines, 16 bit textures.

**Comment by aiunderstand** [comment]
Conclusie: Bottleneck is CPU en Memory.

GPU: GPU doet vrijwel niets doordat er er met weinig verschillende materialen en textures gewerkt wordt.
CPU: Vele script geoptimized, met name voor verkeer. Bottleneck zit nu in memory (~1,4 GB in geheugen) en grootte van dataset om door te geven aan GPU door de CPU.

Vele dingen uitgezocht en geprobeerd in Unity voor de belangrijkste technieken om CPU load te verkleinen die boven genoemd zijn. Unity Asset SECTR gekocht en onderzoek of ik Occlusion Culling kan toepassen mbv CityEngine Tiles mbv SECTR VIS en Tiles kan streamen met SECTR Stream.

Lage prio.

**Comment by aiunderstand** [comment]
Combinatie Frustum Culling en CullingGroups (tile/sector culling) zorgen voor goede 30+ fps framerate.

**Comment by tomvantilburg** [comment]
Gek genoeg kunnen niet alle laptops alle scenarios aan.
We hebben nu stickers op de laptops geplakt voor het juiste scenario. Verder ok.
