### ISSUE TITLE
Plaatjes toevoegen bij eigenschappen

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/rws-imagine#107]
Alleen Renewabad heef nu de juiste plaatjes bij de eigenschap kaartjes.
Moet een beetje omgescreven worden in de properties.json

**Comment by edfennema** [comment]
Even on hold zetten totdat we er zeker van zijn dat alle objecten zijn goedgekeurd.

**Comment by aiunderstand** [comment]
@edfennema Bump voor deze issue nav besproken final lijst RWS op woensdag

**Comment by tomvantilburg** [comment]
Dit lijkt me prio 1, maar ik wacht nog even totdat alle juiste plaatje bekend zijn.
@edfennema : graag finale lijst met plaatjes aanleveren.

**Comment by tomvantilburg** [comment]
Klaar om te testen,maar volgens mij zijn ze ok.

**Comment by tomvantilburg** [comment]
Niks meer van gehoord.
