### ISSUE TITLE
Grote vrouw in Communicity

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/rws-imagine#108]
Het is echt een _hele_ grote vrouw.

Wordt alleen zichtbaar als je 1x bent ingezoomd.

**Comment by aiunderstand** [comment]
Fixed, zat in koppeling camera en zoom level zodat een object meeschaalt wanneer uitgezoomd wordt. In dit geval niet echt wenselijk -> Disabled.

**Comment by tomvantilburg** [comment]
Nooit meer wat van gezien. Ze is weg....
