### ISSUE TITLE
Element in het midden is moeilijk aanklikbaar.

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/rws-imagine#111]
Het waren vroeger meerdere objecten maar lijkt nu 1 object geworden.

**Comment by aiunderstand** [comment]
Hoewel het losse objecten zijn, was de ondergrond ook gekleurd. Die is nu aangepast waardoor het weer losse objecten lijken.

**Comment by MichelPaardekooper** [comment]
Getest en werkt prima
