### ISSUE TITLE
Connectie tussen selecteren eigenschap en inhoud draaikaartje

### ISSUE THREAD

**Issue by edfennema** [Geodan/rws-imagine#112]
Het zwaarste punt van de 18e was de connectie tussen een object selecteren en de info (plaatje object en tekst) op het draaikaartje. Vandaar prio 1. Een audio signaal bij het succesvol selecteren is reeds als issue benoemd, maar ook het vergroten of kleuren van het kaartje dan wel het langzamer laten draaien en nog even blijven bewegen zijn denkbaar.  Ik meen dat Jeffrey de kaartjes ontwikkeld heeft. Mogelijkerwijs kan hij dit voor zijn rekening nemen.

**Comment by aiunderstand** [comment]
Issue bestaat uit 2 onderdelen:

Steven: Ik heb een (zelfde) "achievement"audioclip geplaatst onder elke eigenschap
Tom: Kaartjes langzamer omdraaien en bounce effect voor 5 seconden (zelfde fx als bij score scherm cirkel)

**Comment by tomvantilburg** [comment]
@edfennema : Ik snap nog niet wat wordt bedoeld met 'bounce effect'. Mijn voorstel zou zijn om het kaartje een paar seconden zeer groot af te beelden.

**Comment by edfennema** [comment]
Bouncing is stuiteren. Wat mij voor de geest stond was dat het kaartje stuitert en daardoor steeds groter wordt (eigenlijk is pumping een beter woord) en dan terugzakt naar normaal weergave niveau.

**Comment by edfennema** [comment]
Het geluid dat ik tot nu hoorde ....was dat  een probeersel of vinden jullie dat echt mooi?

**Comment by tomvantilburg** [comment]
Mmm, dat stuiteren gaat 'm niet worden hoor... ;-) Kost veel te veel werk.
Maar ik zal het kaartje tijdelijk groter maken.

**Comment by edfennema** [comment]
Kleurtje aan kaartje geven? Per thema? Of is dat veel werk? (was een rws verzoek)

**Comment by tomvantilburg** [comment]
Kaartjes zijn nu transparant voordat ze omdraaien.

**Comment by tomvantilburg** [comment]
Kaartje komt nu beeldvullend naar voren en blijft een paar seconden staan.

**Comment by tomvantilburg** [comment]
Goeggekeurd
