### ISSUE TITLE
Onderzoeken orientatie

### ISSUE THREAD

**Issue by edfennema** [Geodan/rws-imagine#113]
Spelers lijken vaak behoefte te hebben aan 'terug naar af' of in elk geval aan een centraal oriëntatiepunt. Terug naar af (reset) lijkt haken en ogen te hebben, naar een centraal, opvallend gekleurd, herkenbaar punt zou ene oplossing kunnen bieden.

**Comment by aiunderstand** [comment]
Heb een reset knop gemaakt, moet getest worden

**Comment by tomvantilburg** [comment]
Yep, het het zelf gezien. Werkt.
