### ISSUE TITLE
Verhouding draaikaartgrootte en achtergrond map

### ISSUE THREAD

**Issue by edfennema** [Geodan/rws-imagine#114]
Omdat we de draaikaartjes nu steeds op 24' monitoren laten zien en de leesbaarheid intact moet blijven, vullen de draaikaartjes thans het hele scherm. Op een presentatiescherm (vgl. omvang cursusruimte) kan die verhouding worden aangepast naar meer map, zodat Amalut en de tile die wordt gespeeld beter zichtbaar is. Kan dit in de cursus ruimte worden getest - vanwege het feit dat de finale oplevering in december daar plaatsvindt?

**Comment by tomvantilburg** [comment]
Ik heb daar sterke twijfels over, omdat de resolute van de beamers vaak minder goed is dan de schermen en de tekst is nu al vrij priegelig. We gaan het testen maar verwacht er niet te veel van.

**Comment by tomvantilburg** [comment]
Net samen met Ed getest, de kaartjes zijn ok nu op de beamer in de cursusruimte maar moeten zeker niet kleiner worden.
