### ISSUE TITLE
Tweede scherm popup breekt als je snel achter elkaar iets vindt

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/rws-imagine#128]
TimeOut lijkt een probleem te worden dan.

**Comment by tomvantilburg** [comment]
Zou nu gefixt moeten zijn. Was een polymer dingetje.

**Comment by tomvantilburg** [comment]
Nog steeds een polymer dingetje. Polymer bug zelfs lijkt het....

**Comment by stvno** [comment]
Als je entry-animation="scale-up-animation" en exit-animation="fade-out-animation" weghaalt lijkt het wel te werken

**Comment by tomvantilburg** [comment]
Inderdaad, dat werkt wel.
Animatie is er nu uitgesloopt. Jammer maar 't is niet anders voor nu.
