### ISSUE TITLE
Water in Unity maakt puzzelscherm traag

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/rws-imagine#131]
Indien er water in beeld was bij de overgang van unity naar het puzzelscherm wordt het schuiven van de kaartjes in de puzzel zeer traag.

**Comment by stevenfruijtier** [comment]
Probleem lijkt opgelost door in de NVidia instellingen (NVidia Control Panel) aan te geven dat Firefox en de Plugin-container van Firefox de NVidia processor moeten gebruiken (zie screenshot).

![firefox_nvidia](https://cloud.githubusercontent.com/assets/14315064/12263728/d32aea5e-b931-11e5-8a91-78b9103b7079.png)

**Comment by tomvantilburg** [comment]
Whoops, toch niet opgelost.
Het lijkt erop dat het 'soms' nog misgaat. Steven maakt nu een build zonder water.

**Comment by tomvantilburg** [comment]
We hebben nog 10 x getest. Het lijkt alleen te gebeuren als we binnen een paar seconden doorgaan van 3d naar puzzelscherm door de slider snel naar beneden te schuiven. Dit is een situatie die in de praktijk waarschijnlijk niet voor zal komen.
Voorstel: niets meer aan doen

**Comment by tomvantilburg** [comment]
Dit gaat verholpen worden door de webgl versie (naar ik aanneem).
