### ISSUE TITLE
Verkeerde teksten ingevoerd?

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/rws-imagine#134]
Er is een vermoeden dat de teksten nog oud zijn (ergens zit bijv 'kunnen worden' in).
@edfennema checkt dit met Jan

**Comment by edfennema** [comment]
Ik heb van Jan een review ontvangen met enkele wijzigingen. Teksten waren gewoon de nieuwe, maar blijkbaar nog steeds niet foutloos aan ons aangeleverd. Hoe kan ik die wijzigingen invoeren (d.w.z. zonder dat het jou tijd kost)?

**Comment by tomvantilburg** [comment]
Done, nieuwe teksten zijn ingevoerd.
Heb extra gelet op speciale karakters, die zien er ook goed uit.

**Comment by edfennema** [comment]
Top

Op 20 januari 2016 14:16 schreef Tom van Tilburg notifications@github.com:
