### ISSUE TITLE
Startscherm voor elk van de steden 

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/rws-imagine#28]
SF: Is er al iets van een startscherm waarna de steden beginnen te spelen?
Nu ga je naar bv http://research.geodan.nl/sites/imagine/tafels/Sprawville en begint gelijk het spel te spelen. Is het veel werk om hier een soort van startpagina voor te zetten?

**Comment by aiunderstand** [comment]
Ik heb een startscherm gemaakt met een dynamische achtergrond. Nu nog met placeholder voor check of cow verbonden is, maar uiteindelijk met werkende code erachter. Ik kan me voorstellen dat ik ook een call doe naar de 2D api met als melding welk thema gekozen is voor deze tafel.

![levelselect](https://cloud.githubusercontent.com/assets/6376127/9908919/266c1b46-5c96-11e5-97c7-f1a25c5e7c4e.png)

**Comment by stvno** [comment]
Er moet geen select level optie zijn in het startscherm. De beoogde gebruiker moet gewoon op start kunnen klikken en beginnen. Verder is het niet de bedoeling dat er ergens de naam van de stad zichtbaar is, dat is om discussie over de naamgeving te voorkomen

**Comment by stvno** [comment]
Verder is het voor de gebruiker volstrekt niet relevant of cow connected is of niet, hij weet niet wat dat betekent en wat hij met de informatie aanmoet, kan evt in een debug console oid

**Comment by stvno** [comment]
Er is een startscherm, er moet allen voor elke stad een film worden gemaakt die getoond kan worden

**Comment by tomvantilburg** [comment]
Volgens @edfennema komt er geen film in het startscherm.
De huidige film (big buck bunny) moet vervangen worden door het plaatje van de stad (dus zoals het score scherm.

**Comment by tomvantilburg** [comment]
De film is er al weer een tijdje uit. Graag testen of het zo ok is.

**Comment by tomvantilburg** [comment]
Geen commentaar meer op gehad.
