### ISSUE TITLE
Reset button 

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/rws-imagine#29]
Is het moeilijk om aan de pagina's van de steden een 'reset knop' toe te voegen? Deze zou dan het scherm van het team dat op dat moment speelt moeten leegmaken (niet alle teams dus zoals bij een F5 denk ik gebeurt).

**Comment by stvno** [comment]
Moet dit op de speelpagina komen of in de beheertool? (waar hij volgens mij al zit)

**Comment by tomvantilburg** [comment]
Deze knop zit inderdaad al in de beheertool (monitorscherm). Dat lijkt mij voldoende?

**Comment by stvno** [comment]
werkt (verder doet F5 trouwens geen full reset van alle spelers op de tafel)
