### ISSUE TITLE
Scorescherm met stemverdeling 

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/rws-imagine#30]
Er is toch al een scherm met alle scores? Kunnen hier ook de beschikbare stemmen aan toegevoegd worden (een vast percentage van de score)?

**Comment by tomvantilburg** [comment]
Het score scherm ziet er nog niet zo geweldig uit, het past bijvoorbeeld niet op 1 scherm.
Ik ga een nieuw scherm maken waar het allemaal wat overzichtelijker is.

**Comment by tomvantilburg** [comment]
Overigens waren de stemmen al verwerkt in he scorebord zie ik.
@stevenfruijtier , kan je dit bevestigen?
Zie: http://research.geodan.nl/sites/rws-imagine/scores.html

**Comment by stvno** [comment]
De stemmen in het scorebord zijn gewoon 75% van de score, dat betekent dat het het aantal stemmen is die men op die tafel heeft gekregen, er is dus geen methode om het totaal aantal stemmen te tonen, of tijdens het tweede deel van het spel de herverdeling van stemmen en/of punten

**Comment by tomvantilburg** [comment]
Stemverdeling was 60/40 toch?
Er komt een nieuw scherm met de totale stemverdeling.

**Comment by tomvantilburg** [comment]
Er is nu een testbare versie. Graag testen dus!
http://research.geodan.nl/sites/imagine/pitchlist.html

**Comment by tomvantilburg** [comment]
Geen opmerkingen gehad, afgesloten.
