### ISSUE TITLE
team volgorde

### ISSUE THREAD

**Issue by stvno** [Geodan/rws-imagine#45]
De verschillende tafels hebben verschillende volgordes van teams die komen spelen:

communicity: A>D>C>B
planopolis: B>A>D>C
renewabad: C>B>A>D
sprawlville: D>C>B>A

Echter in imagine-thegame is er maar 1 volgorde mogelijk, dat moet worden aangepast zodat per tafel een andere volgorde bestaat

**Comment by tomvantilburg** [comment]
Was vergeten teams toe te voegen als attribute. Zou nu weer goed moeten werken.

**Comment by stvno** [comment]
gefixt
