### ISSUE TITLE
Nieuws stadsnamen toepassen

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/rws-imagine#47]
Cyaanstad (solidariteit) (RGB 90, 187, 209)
Magenta-stad (economisch groei) (RGB 209, 17,138)
Groene stad (eco groei) (RGB 129, 166, 46)
Gele stad (eilandrijk) (RGB 236, 170, 34)

**Comment by tomvantilburg** [comment]
Plannedopolis -> 5ABBD1
Sprawlville -> D1118A
Renewabad -> 81A62E
Communicity -> ECAA22

**Comment by edfennema** [comment]
Hallo, testing.

**Comment by tomvantilburg** [comment]
Stadsnamen zitten er nu overal goed in.
@edfennema graag nog even feedback of het overal duidelijk genoeg is over welke stad het gaat (maw.: zit de naam er vaak genoeg in?)

**Comment by tomvantilburg** [comment]
Geen opmerkingen gehad, afgesloten.
