### ISSUE TITLE
Tijd loopt al als scorescherm nog open staat

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/rws-imagine#49]
Als je nog in het scorescherm of in de unity player zit dat loopt de tijd voor de kaartjes al.

Die mag pas gaan lopen na de unity player.

**Comment by tomvantilburg** [comment]
Dit was waargenomen door @stevenfruijtier maar ik kan het niet meer reproduceren.

**Comment by stvno** [comment]
Die bug zat in een oude versie van rws-imagine die moet er al uit zijn, ik kan hem iig niet reproduceren
