### ISSUE TITLE
Focus op geselecteerd kaartje bij verbinden 

### ISSUE THREAD

**Issue by edfennema** [Geodan/rws-imagine#52]
Wanneer de speler in verbinding / stempel mode speelt, is het prettig als een geselecteerd kaartje dat onder een ander kaartje ligt naar boven komt  - om het nog eens te kunnen lezen. In de pitchlist gebeurt dat al wel, maar tijdens het spelen niet.

**Comment by tomvantilburg** [comment]
Lukt bij mij nog niet. Het is sowieso lastig om te linken vanaf een onderliggend kaartje, hij pakt dan vaak het kaartje erbovenop.

**Comment by tomvantilburg** [comment]
Werkt nu wel bij mij !

**Comment by edfennema** [comment]
Bij mij ook!

**Comment by tomvantilburg** [comment]
Dan maggie dicht
