### ISSUE TITLE
Verbindingen / stempels tonen in pitchlist

### ISSUE THREAD

**Issue by edfennema** [Geodan/rws-imagine#53]
Als het team een pitch houdt, dan laten ze zien welke kaartjes ze hebben gekozen. De verbindingen en stempels zijn daarbij nu nog niet zichtbaar, terwijl die de pitch juist ondersteunen (sterker, de enige reden om nu te verbinden en te stempelen is die pitch). Graag zichtbaar maken.

**Comment by tomvantilburg** [comment]
Stempels worden nu getoond door een licht rode tint in de reviewboard kaartjes

**Comment by edfennema** [comment]
Ja, dat is mooi.

**Comment by tomvantilburg** [comment]
Links doen het nu ook, 
Valt te testen in de pitch van Gele stad Team C

**Comment by edfennema** [comment]
Ziet er voor vandaag 24-9 toch al heel werkbaar uit

**Comment by tomvantilburg** [comment]
Geen opmerkingen gehad, afgesloten.
