### ISSUE TITLE
Knop van volgende team zit op zelfde locatie als einde slider, mogelijk probleem

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/rws-imagine#55]
Als je de slider per ongeluk nog een keer in wilt drukken terwijl hij net klaar is, druk je al op de knop van het volgende team (is al een paar keer voorgekomen). Knop van volgende team zou net op een andere plek moeten zitten.

**Comment by stvno** [comment]
Of de knop pas na een paar seconden laten zien?

**Comment by tomvantilburg** [comment]
Nog mooier.

**Comment by stvno** [comment]
Er zit een vertraging van 2s in voordat hij getoond wordt

**Comment by tomvantilburg** [comment]
Sjiek!
