### ISSUE TITLE
Dragging veel stroever als kleur transitie aanstaat

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/rws-imagine#58]
Als je bijivoorbeeld meer dan 20 kaartjes op het veld hebt dan heeft het volgende kaartje geen kleurtransitie meer en loopt veel soepeler.
Misschien is het de moeite waait om de transitie ook uit te zetten voor alle kaartjes

**Comment by stvno** [comment]
Je mag ook maar 20 kaartjes neer leggen, de daar op voglende kaartjes doen niet mee, vandaar geen transitie

**Comment by tomvantilburg** [comment]
Correct, het was alleen ter illistratie. Het verschil is best wel groot.

**Comment by tomvantilburg** [comment]
uiteindelijk speelt dit probeel alleen in Chrome, en dat gebruiken we niet voor de game
Afgesloten.
