### ISSUE TITLE
Toekenning punten na pitches

### ISSUE THREAD

**Issue by edfennema** [Geodan/rws-imagine#60]
Na het pitchen kunnen willekeurig punten worden gegeven, los van het maximaal aantal dat een team kan verdelen. Bijv een team dat 60 punten kan verdelen zou zomaar een veelvoud daarvan kunnen toekennen. Waarschuwing of blokkeren zou handig zijn.

**Comment by tomvantilburg** [comment]
Er staat nu een reminder met het totaal aantal punten om weg te geven voor een team.
Voor nu is dat voldoende. Graag nog even testen.

**Comment by tomvantilburg** [comment]
Geen klachten gehad. Sluiten dus...
