### ISSUE TITLE
In speelbord verwerken van tijd en impact aanduiding

### ISSUE THREAD

**Issue by edfennema** [Geodan/rws-imagine#62]
Op het speelbord in donkerder grijs de woorden 'Tijd' en 'Mate van versterkende invloed' verwerken (resp. rechtsonder, horizontaal geschreven en linksboven, verticaal gedraaid), ondersteund door een korte lijn (zie attachment)
![field time impact](https://cloud.githubusercontent.com/assets/14315121/10216678/25389baa-682b-11e5-8e83-ab78df3ae26e.png)

**Comment by edfennema** [comment]
In plaats van dat lelijke 'Mate van versterkende invloed' mag het ook iets zijn als ''Verklarende Waarde".

**Comment by edfennema** [comment]
Hoi Steven O, kan jij dit bewerkstelligen? Het mag ook gewoon IMPACT en TIJD zijn (lijkt me zelfs het beste). Dank voor een response. Groetjes, Ed

**Comment by edfennema** [comment]
Tom, Steven geeft aan dat jij kan (pre)viewen.

**Comment by tomvantilburg** [comment]
Ziet er prima uit.

**Comment by tomvantilburg** [comment]
Toch niet prima, het zit er alleen voor het eerste team in. Andere drie moeten nog.

**Comment by stvno** [comment]
Dat kan niet, het is op het niveau van het element imagine-ppuzzel gedaan. Bij mij zie ik de tekst in alle vier de steden, browsercache? Of wordt het element niet meer gedeeld?

**Comment by tomvantilburg** [comment]
Voorwaar, ik zeg u: na het legen van de cache is er nog steeds geen tekst zichtbaar. Ik kan ook niet zo snel uitvinden in de elements waar het zou moeten zitten. Waar kan ik kijken?

**Comment by stvno** [comment]
Het is deze commit: https://github.com/Geodan/rws-imagine/commit/d48a93ad4f4eb57200a527880d80bb727e0d6d85 
De functie WriteText op regel 650 e.v.

**Comment by tomvantilburg** [comment]
Volgens mij wordt de canvas gereset in de _statechange . Iets met clearRect

**Comment by stvno** [comment]
Ah natuurlijk, dit kan inderdaad niet werken. Krijg je ervan als je niet het hele spel test ;) Ik zal even een fix schrijven

**Comment by edfennema** [comment]
Top!

**Comment by tomvantilburg** [comment]
Ik gebruik nu de nieuwe versie maar ik zie echt nog geen tijd en impact in borden anders dan de eerste.
Zit die writeText wel op de goeie plek? Ik zie 'm nu alleen in de 'attached' en de 'drawVerbindingen' zitten. Die attached wordt volgens mij maar 1 keer aangeroepen en die drawVerbindingen snap ik niet.

**Comment by tomvantilburg** [comment]
Yes, werkt nu in alle team borden.
