### ISSUE TITLE
Pinch zoom uitschakelen in speelscherm

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/rws-imagine#63]
Als je met twee vingers tegelijk sleept, beschouwt de browser dat als een pinch zoom.
Dat moet uitgeschakeld worden.

**Comment by tomvantilburg** [comment]
Zie: https://support.mozilla.org/nl/questions/952203

**Comment by tomvantilburg** [comment]
Indien uitschakelen van de pinch ook van invloed is op Unity, dan heeft Unity prioriteit en laten we het 2D voor wat het is.

**Comment by tomvantilburg** [comment]
Getest: het is heel eenvoudig uit te schakelen door de pinch.in en de pinch.out op null te zetten in about:config -> gestures

**Comment by aiunderstand** [comment]
Still an issue?

**Comment by tomvantilburg** [comment]
Ja, nog 2 laptops te gaan ;-)

**Comment by aiunderstand** [comment]
Gefixt door Tom. Close
