### ISSUE TITLE
Stedennamen in het NL

### ISSUE THREAD

**Issue by edfennema** [Geodan/rws-imagine#66]
Waar de stadsnamen zichtbaar verschijnen dienen de volgende NL teksten te worden gebruikt:

-Plannedopolis  = De geplande stad
-Sprawlville = De onbegrensde stad
-Renewabad = De cyclische stad
-Communicity = De zelfvoorzienende stad

**Comment by tomvantilburg** [comment]
Dit is echt wel de laatste keer dat we stedennamen gaan aanpassen.
Ze worden gelukkig maar zeer spaarzaam gebruikt.

**Comment by tomvantilburg** [comment]
Namen zijn aangepast in de pitchlijst.
Graag testen:
http://research.geodan.nl/sites/imagine/pitchlist.html

**Comment by tomvantilburg** [comment]
Geen commentaar meer op gehad. Lijkt me goed.
