### ISSUE TITLE
Kleurenblindheid kaartjes

### ISSUE THREAD

**Issue by edfennema** [Geodan/rws-imagine#67]
Zoals aan Steven O gevraagd: 

Namens een aantal kleurenblinde deelnemers is uit RWS het verzoek gekomen om de kleuren van de schuifkaartjes op het 2D speelveld uit te voeren in de kleuren blauw, oranje, rood en groen (deels klopt dat al, maar geel en paars moeten dan oranje en blauw worden ).

Graag willen we onze sympathie voor deze groep op dinsdag 10 nov al laten zien en mijn vraag is of het mogelijk is om die kaderkleuren nog aan te passen?

**Comment by stvno** [comment]
Met mijn kleurenblindheid tool http://colororacle.org/ zie ik niet direct wat jullie hier bedoelen. Rood en groen zijn de moeilijkste kleuren voor kleurenblinden,dus het lijkt me niet handig om rood/groen te doen.

**Comment by tomvantilburg** [comment]
Rood en Groen lijkt me niet de beste combi nee :-/ 
Wat zouden ze in gedachten hebben gehad bij RWS?

**Comment by stvno** [comment]
Ik heb nu in ieder geval de vier categorieen in colorblind safe palette gemaakt (spuuglelijk maar ja) in ieder geval deuteranopia, protanopia en tritanaopia moeten het onderscheid kunnen zien. De themakleuren per stad heb ik niet aangezeten, het lijkt me daar minder relevant of je onderscheid kan zien, omdat je uberhaupt fysiek op een andere tafel bent.

**Comment by edfennema** [comment]
OK, many tx
