### ISSUE TITLE
Finale versie events en kenmerken plaatsen voor 10 nov

### ISSUE THREAD

**Issue by edfennema** [Geodan/rws-imagine#68]
De finale versies van de events (incl tijd en scores) en eigenschappen zijn opgeleverd. De events staan in Concept scoring v3 (Google rekenblad gedeeld met Tom) en de eigenschappen staan in het script dat aan Tom is aangeleverd. Graag plaatsen (zoals afgestemd).

**Comment by tomvantilburg** [comment]
Ze zitten erin. Graag testen.

**Comment by tomvantilburg** [comment]
Testen op:
http://research.geodan.nl/sites/imagine/tafels/Renewabad/index.html
(met chrome!!)

**Comment by tomvantilburg** [comment]
Geen klachten meer over gehoord.
