### ISSUE TITLE
Groepjes mensen plaatsen

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/rws-imagine#70]
In plaats van de verwijderde voetgangers

**Comment by tomvantilburg** [comment]
Er staat nu 1 groepje mensen verborgen, dat mogen er nog meer worden

**Comment by aiunderstand** [comment]
Overal staan nu mensen waar mensen een eigenschap zijn (alle steden behalve sprawlville)

**Comment by tomvantilburg** [comment]
Zit erin
