### ISSUE TITLE
Laadtijd assets verbeteren

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/rws-imagine#73]
Als de assets via een (remote) webserver ingeladen worden dan duurt dat heeeel lang. Uitproberen of we de assets lokaal kunnen neerzetten.

**Comment by tomvantilburg** [comment]
Op een lokale server duurt het nu minder dan een minuut voor renewabad. Dat lijkt me acceptabel, zeker als we de 3D omgeving draaiende houden op de achtergrond na de eerste keer laden

**Comment by edfennema** [comment]
Wat is er tegen om de assets echt lokaal op de laptop zelf te zetten (# mogelijke instabiliteit netwerk)?

**Comment by aiunderstand** [comment]
Asset staan lokaal op de laptop (net zoals de server). Laadtijd komt door grote hoeveelheid data die uitgepakt wordt in geheugen (+- 1,4 GB). Zelfde als Issue 101
