### ISSUE TITLE
Eigenschappen instellen voor klikbare objecten

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/rws-imagine#76]
Via een scriptje moeten alle klikbare objecten automatisch groen worden als ze ingeladen worden.

**Comment by tomvantilburg** [comment]
Er lijken nog wat eigenschappen onvindbaar in de 3D weergave

**Comment by edfennema** [comment]
Groen was wegens Renewabad. Krijgen objecten in andere steden dan andere kleuren? Of kleuren geheel verwijderen, want het flonker effect zegt wat er klikbaar is? Please comment.

**Comment by aiunderstand** [comment]
Alle klikbare objecten krijgen de kleur van de stad. Na klik worden ze wit.
