### ISSUE TITLE
Gespeelde tegel activeren in achtergrondfilm

### ISSUE THREAD

**Issue by edfennema** [Geodan/rws-imagine#80]
Als een tegel wordt gespeeld, toont de film op zoom 1 niveau de tegel in kwestie ingekleurd o.i.d. Er zijn dan dus 4 films met elk een andere ingekleurde tegel/gebiedje.

**Comment by aiunderstand** [comment]
Dit moet nog gemaakt worden. 

@edfennema wie gaat dit doen en hoe wil je dit precies

**Comment by tomvantilburg** [comment]
Steven is films aan het maken.

**Comment by aiunderstand** [comment]
Alle filmpjes zijn gemaakt, nu @tomvantilburg die de filmpjes plakt in 2D

**Comment by tomvantilburg** [comment]
Zit erin, ziet er ok uit.
