### ISSUE TITLE
Straat geluid van 2D ook achter 3D plaatsen?

### ISSUE THREAD

**Issue by edfennema** [Geodan/rws-imagine#81]
In 2D wordt straatgeluid weergegeven. Kan dat ook als achtergrond bij 3D?

**Comment by aiunderstand** [comment]
Er is een audio systeem ingebouwd, de 2D geluiden worden erin verwerkt.

**Comment by aiunderstand** [comment]
Gedaan.

**Comment by MichelPaardekooper** [comment]
Getest, er is achtergrondgeluid
