### ISSUE TITLE
De tijd in unity player loopt al voordat de user in het spel zit

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/rws-imagine#82]
Voordat je op de knop met de naam van je team klikt laadt de 3D omgeving al. Dat is aan de ene kant gunstig omdat je niet onnodig hoeft te wachten maar aan de andere kant onhandig omdat je al speeltijd kwijt bent.
Samen laten vallen met issue #46 omdat de timer (en meer) daar ook gereset moet worden.

**Comment by aiunderstand** [comment]
Reset function ingebouwd API:
u.getUnity().SendMessage("Virtual Time System", "ResetTime", "");

**Comment by tomvantilburg** [comment]
@aiunderstand : hoe kan dit getest worden?

**Comment by tomvantilburg** [comment]
Blijkt dat er een freakin jquery scriptje ervoor zorgt dat de unity plugin gereset wordt. 
$('#firstScreen').slideUp();
Is nu uitgezet en apart genoeg slide de puzzel nog steeds up maar blijft de unity instance in leven.

**Comment by tomvantilburg** [comment]
slideUp is weer teruggezet omdat unity teveel resources vreet tijdens de puzzel.

**Comment by aiunderstand** [comment]
De Reset functie pauseert de game engine en disabled de camera zodat ook cpu load teruggegeven worden. Memory footprint blijft natuurlijk. Testen

**Comment by tomvantilburg** [comment]
Dit hebben we getest, Werkte na nog wat aanpassingen.
