### ISSUE TITLE
Auditieve beloning op het vinden van een draaikaartje

### ISSUE THREAD

**Issue by edfennema** [Geodan/rws-imagine#85]
Om de connectie tussen 3D wereld en de draaikaartjes te bevorderen zou een piepsignaal kunnen worden gekoppeld aan het draaien van het kaartje.

**Comment by edfennema** [comment]
Prio 1 restored omdat dit tijdens de laatste test op 18 november als meest heikele punt is aangemerkt. Zie ook issue 112.

**Comment by aiunderstand** [comment]
Gedaan

**Comment by MichelPaardekooper** [comment]
Getest, geluidjes zijn aanwezig
