### ISSUE TITLE
Nachtbeleving

### ISSUE THREAD

**Issue by edfennema** [Geodan/rws-imagine#86]
Meerdere mensen (4) ervaren het spelen van renewabad als een nachtelijke bezigheid, terwijl we 8 minuten in daylight spelen. Niet iedereen voelt dit zo, maar heeft denkelijk met optimalisatie te maken. Wel een issue denk ik voor alle steden.

**Comment by aiunderstand** [comment]
Naar aanleiding van gesprek besloten tot dag beleving. Start met dag ( rond 11.00u - 17.00u) voor 4 minuten dan 30 seconden van 17.00-11.00 volgende dag, tot slot weer 4 minuten 11.00-17.00u

**Comment by aiunderstand** [comment]
Boven op Virtual Time System nu een RWS specifieke configuratie gemaakt waardoor er exact 10 minuten is, 4 min 45 Dag, dan 30 seconden Nacht en dan weer 4.45minuten Dag

**Comment by MichelPaardekooper** [comment]
Getest, nacht is niet meer donker en veel korter
