### ISSUE TITLE
Intekenen routes plannedopolis

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/rws-imagine#87]
Routes moeten ingetekend worden voor plannedopolis, zelfde aanpak als Renewabad.

**Comment by tomvantilburg** [comment]
@edfennema , kan jij aangeven of er nog bijzondere kenmerken aan de routes moeten zitten voor plannedopolis (alleen wat betreft de locatie van de route)

**Comment by edfennema** [comment]
Ik zend jullie zometeen een korte ppt met voertuigen en delen waar ze moeten rijden, lopen etc.

**Comment by tomvantilburg** [comment]
Routes ingetekend door michel. Staan klaar in 
\luna\users\Tomt\route_plannedopolis_zoom3.csv

@aiunderstand : graag testen

**Comment by tomvantilburg** [comment]
Eerste test ziet er niet slecht uit. 
Voorlopig zo laten.

**Comment by tomvantilburg** [comment]
Goed genoeg
