### ISSUE TITLE
Routes tekenen sprawville

### ISSUE THREAD

**Issue by aiunderstand** [Geodan/rws-imagine#92]

**Comment by tomvantilburg** [comment]
Eerste test ziet er redelijk uit. Nog wijzigen:
- trein moet hoogte van rails aan blijven houden
- sommige auto's kleiner schalen en roteren @aiunderstand 
- pivot points aanpassen (bus) @aiunderstand

**Comment by aiunderstand** [comment]
pivot points en schaal gefixt

**Comment by tomvantilburg** [comment]
Goed genoeg
