### ISSUE TITLE
Routes tekenen communicity

### ISSUE THREAD

**Issue by aiunderstand** [Geodan/rws-imagine#93]

**Comment by tomvantilburg** [comment]
Routes zijn getekend en aangeleverd, was nog even lastig omdat er ook relief in dit scenario zit.
Graag testen.

**Comment by tomvantilburg** [comment]
Aanpassingen noodzakelijk:
- Rekening houden met wegafzettingen
- Een van de autos zit in het wegdek

**Comment by tomvantilburg** [comment]
Nieuwe routes staan klaar in 
\luna\users\Tomt\route_communicity_zoom3.csv
Graag testen.

**Comment by tomvantilburg** [comment]
Snotje... het stratenplan is natuurlijk volledig gewijzigd in de laatste versie. Die routes moeten opnieuw getekend. 
@azarakhshr : mag ik het nieuwe stratenplan EN de roadblocks van communicity?

**Comment by azarakhshr** [comment]
Dag Tom,

De nieuwe routes en straat construction signs in FGBD zijn hier:

X:\SR\SDP15004 RWS Imagine\11
CityEngine\Communicity\Zoom3\FGDB_StreetsAndConstructionSigns

De straaten met construction signs moeten geen verkeer bevatten.

De straaten met 1 meter breedte moeten ook geen verkeer hebben.

Laat het mij graag weten als er onduidelijkheiden er zitten.

Groetjes,
Azarakhsh

Op 10 december 2015 12:20 schreef Tom van Tilburg notifications@github.com
:

**Comment by tomvantilburg** [comment]
Nieuwe routes nieuwe kansen:
\luna\users\Tomt\route_communicity_zoom3.csv
- boot1 toegevoegd
- geen routes over smalle wegen
- (bijna) geen botsing met wegblokkades meer

@aiunderstand : graag testen

**Comment by tomvantilburg** [comment]
Bijna goed, de bootjes moeten nog 'ont-snapped'  worden...

**Comment by tomvantilburg** [comment]
Nieuwe versie staat klaar om te importeren en testen. Zelfde plek.

**Comment by tomvantilburg** [comment]
Goed genoeg
